version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      angular:
        patterns:
          - "@angular*"
      capacitor:
        patterns:
          - "@capacitor*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
