#!/usr/bin/env node
/**
 * Fails a colour that does not come from the theme's tokens.
 *
 * src/styles.scss declares every colour the app paints as a custom property,
 * and the dark theme and the two high-contrast blocks redeclare them. A
 * colour written anywhere else — `#9ca3af` in a component stylesheet,
 * `text-gray-400` in an `@apply` or a template, `'rgba(34, 197, 94, 0.1)'` in
 * a chart dataset — is painted the same in every one of those modes, and
 * nothing in the build notices. It renders, no spec measures it, and a
 * screenshot taken in the author's own theme looks right. That is how the
 * tree came to hold hundreds of them, many of them under AA in one theme or
 * the other: gray-400 meta text at 2.29:1 on the light card, a primary icon
 * at 2.72:1 on the dark dialog. check-contrast.mjs scores the pairs somebody
 * listed; this gate is what keeps a colour from being painted outside them.
 *
 * Four rules, over `src/app/**` (`.scss`, `.html`, `.ts`; specs and
 * `testing/` helpers excluded) and src/styles.scss:
 *
 *   - **Palette utilities.** A Tailwind colour utility — a prefix (`text`,
 *     `bg`, `border`, `ring`, `from`, `fill`, …), a palette name, an optional
 *     shade and an optional `/alpha`, behind any variant chain — in an
 *     `@apply` or a stylesheet value, in a template's `class`, `[class]`,
 *     `[ngClass]` or `[class.<utility>]`, and in any TypeScript string. The
 *     theme's own aliases (`text-fg-muted`, `bg-surface-card`, …) are read
 *     from tailwind.config.js and pass, but not with an `/alpha`: a var()
 *     cannot be split into channels, so Tailwind silently generates nothing
 *     for `bg-brand/12`.
 *   - **Literals.** A hex, `rgb()`/`hsl()` or named colour in a stylesheet
 *     value; a hex or functional colour anywhere in an `@apply`, and a named
 *     one inside its arbitrary values (`text-[red]`), as in a class list; and
 *     any colour literal quoted in TypeScript or in a template attribute or
 *     binding, including Tailwind's arbitrary `bg-[#…]`. A
 *     `--mat-*`/`--mdc-*` token given a literal, and white on a rule whose
 *     fill is a token, are named as such because each has a token answer.
 *   - **Fallbacks and mixes.** `var(--declared, #literal)` is dead code that
 *     reads as if it mattered; `var(--undeclared, #literal)` always paints its
 *     fallback, whatever the theme. A `color-mix()` passes only when every
 *     operand is a declared var(), `transparent` or `currentColor`.
 *   - **Bound category colours (#461).** `[style.color]`,
 *     `[style.background-color]`, `[style.backgroundColor]`,
 *     `[style.border-color]` and `[ngStyle]` put a colour on screen that no
 *     stylesheet can see. The category chip corrects its own glyph, so its
 *     bindings are exempt; so is a string-literal `'var(--token)'`.
 *
 * Decisions worth stating, because each has a cheaper alternative that is
 * worse:
 *
 *   - **Counts are per file and per token**, not per file. A per-file number
 *     lets a slice swap `text-gray-500` for `text-slate-500` and pass; keyed
 *     by the matched text, the swap is a new token above the baseline and a
 *     stale one below it, and both fail.
 *   - **Two baselines.** BASELINE freezes the theme debt; BASELINE_CATEGORY
 *     freezes the places a category's own colour is bound or defaulted (the
 *     binding rule's sites, and a literal that is the fallback of a `.color`
 *     read, `category?.color || '#9E9E9E'`), which close under #461 by a
 *     different fix: the chip and the glyph pipes. Both are generated by
 *     `--print-baseline`, both fail stale in both directions — above is a new
 *     colour, below is a ratchet that stopped ratcheting — and both end
 *     empty: a slice that clears a hit deletes its row in the same commit.
 *   - **Allow markers carry a reason, and a table carries a count.** Some
 *     colours are meant to be literal: a provider's logo, a scrim over a
 *     photo, the category data itself. They are marked where they stand —
 *     `colors:allow(<kind>) <reason>` on the line (or, in a template, alone
 *     on the line before a tag, covering that tag up to its `>`), or
 *     `colors:allow-start(<kind>) <reason>` … `colors:allow-end` around a
 *     block. ALLOWED records, per file, the kind and how many hits its
 *     markers exempt, with a reason — a row per kind when a file marks two.
 *     The count goes stale in both directions, a marker that exempts nothing
 *     fails, and an empty reason fails, so a marker cannot quietly widen to
 *     cover a new colour.
 *   - **Declared means declared in a stylesheet.** Every `--*` declared in a
 *     `src` stylesheet, every `--mat-sys-*` (emitted by `mat.theme()`), and
 *     the two set at runtime, listed in RUNTIME_DECLARED with where they are
 *     set. Only the fallback and color-mix rules ask.
 *
 * Exemptions, precisely:
 *   - In src/styles.scss, a declaration of a theme token
 *     (`--surface-* --border-* --text-* --color-* --scrollbar-* --shadow-*
 *     --overlay-*`): that is where the literals belong.
 *   - A system colour (`CanvasText`, `Highlight`, …) inside a
 *     `@media (forced-colors: …)` block, where it is the only right answer.
 *   - Comments, blanked before scanning with offsets kept, so prose about a
 *     colour is not a colour. Markers are read from the raw text for that
 *     reason, and only where it was a comment: a string or an attribute
 *     value that spells one exempts nothing. An inline template is a string
 *     to the lexer, so it is marked by a `//` block around its property.
 *
 * What it deliberately cannot see:
 *   - A colour assembled at runtime from parts (`'#' + hex`, a computed
 *     `rgb()` built from numbers) or read from data. Category colours are
 *     data; the binding rule is what holds them to the chip and the pipes.
 *   - Whether a token is the *right* token. `color: var(--text-muted)` on a
 *     tinted fill passes here and may fail AA; that is check-contrast.mjs's
 *     question, and the rendered specs'.
 *   - A named colour in a TypeScript string that is neither the whole string
 *     nor the value of a colour property in an inline style.
 *   - Which part of a TypeScript template string is a comment. A comment in
 *     an inline `styles:` block is part of the string, so a hex in it is
 *     read as a colour.
 *   - A colour bound through `[style.background]`, `[style.border]`, a
 *     `[style]` object or `[attr.fill]`. The binding rule reads the four
 *     properties a category's glyph or tile is bound through, and `[ngStyle]`.
 *   - Material's own stylesheets, which are not ours to police here.
 *
 * `--print-baseline` prints both baselines for the current tree, sorted and
 * copy-pasteable, and the per-file marker counts ALLOWED must match.
 * `--self-test` runs the scanners over embedded must-hit and must-not-hit
 * fixtures; colors:check chains it ahead of the live scan. As with the other
 * gate scripts there is no .spec.ts: the self-test is the spec.
 *
 * Reference documentation lives in docs/accessibility.md.
 */

import { readFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { createRequire } from 'node:module';
import { join, sep } from 'node:path';
import { pathToFileURL } from 'node:url';

const SOURCE_DIR = 'src/app';
const GLOBAL_STYLESHEET = 'src/styles.scss';
const STYLESHEET_ROOT = 'src';
const DOC = 'docs/accessibility.md';
const SKIP_DIRS = new Set(['node_modules', 'dist', '.angular', 'coverage', 'testing']);

/** The chip corrects its glyph against its own tint (#460), so its bindings are the fix, not the defect. */
const CHIP_FILE = 'src/app/shared/components/category-chip/category-chip.component.ts';

/**
 * The theme's debt, per file and per matched token. Generated by
 * `--print-baseline`; every number is a colour that does not follow the
 * theme, and the only legal edits are downward.
 */
const BASELINE = {
  'src/app/features/about/about.component.scss': {
    'rgba(var(--color-accent-rgb, 63, 81, 181), 0.1)': 1,
    'rgba(var(--color-accent-rgb, 63, 81, 181), 0.2)': 1,
    'rgba(var(--color-primary-rgb, 25, 118, 210), 0.1)': 1,
    'white': 1,
  },
  'src/app/features/ai/import/duplicate-warning/duplicate-warning.component.scss': {
    '#ffc107': 1,
  },
  'src/app/features/ai/import/file-dropzone/file-dropzone.component.scss': {
    '#2196f3': 1,
    '#4caf50': 1,
    '#9c27b0': 1,
    '#f44336': 1,
    'rgba(156, 39, 176, 0.08)': 1,
    'rgba(156, 39, 176, 0.2)': 1,
  },
  'src/app/features/ai/import/import-history/import-history.component.scss': {
    'bg-amber-100': 1,
    'bg-green-100': 1,
    'bg-red-100': 1,
    'bg-red-50': 1,
    'border-gray-100': 1,
    'border-red-200': 1,
    'dark:bg-amber-900/50': 1,
    'dark:bg-green-900/50': 1,
    'dark:bg-red-900/20': 1,
    'dark:bg-red-900/50': 1,
    'dark:border-gray-700': 1,
    'dark:border-red-800': 1,
    'dark:text-amber-300': 1,
    'dark:text-amber-400': 1,
    'dark:text-gray-100': 3,
    'dark:text-gray-400': 3,
    'dark:text-green-300': 1,
    'dark:text-green-400': 1,
    'dark:text-red-300': 3,
    'dark:text-red-400': 2,
    'text-amber-500': 1,
    'text-amber-600': 1,
    'text-amber-700': 1,
    'text-gray-500': 3,
    'text-gray-900': 3,
    'text-green-500': 1,
    'text-green-600': 1,
    'text-green-700': 1,
    'text-red-500': 1,
    'text-red-600': 2,
    'text-red-700': 3,
  },
  'src/app/features/ai/import/import-wizard/import-wizard.component.scss': {
    '#009688': 3,
    '#9c27b0': 3,
    '#e91e63': 1,
    'rgba(0, 150, 136, 0.1)': 1,
    'rgba(156, 39, 176, 0.08)': 1,
    'rgba(156, 39, 176, 0.1)': 1,
    'rgba(156, 39, 176, 0.2)': 1,
    'rgba(255, 255, 255, 0.2)': 1,
    'var(--text-secondary, #666)': 1,
    'white': 1,
  },
  'src/app/features/ai/import/transaction-preview-table/transaction-preview-table.component.scss': {
    'var(--border-primary, #ddd)': 1,
    'var(--border-primary, #e0e0e0)': 2,
    'var(--border-primary, rgba(0, 0, 0, 0.06))': 1,
    'var(--border-primary, rgba(0, 0, 0, 0.16))': 2,
    'var(--surface-background, #f8f9fa)': 2,
    'var(--surface-card, #fff)': 1,
    'var(--surface-hover, #eee)': 3,
    'var(--surface-hover, #f0f0f0)': 1,
    'var(--text-muted, #666)': 6,
    'var(--text-muted, #999)': 2,
    'var(--text-muted, #bbb)': 1,
    'var(--text-primary, #222)': 2,
    'var(--text-secondary, #555)': 1,
  },
  'src/app/features/ai/search-history/search-answer-history.component.scss': {
    'dark:text-gray-400': 1,
    'text-gray-500': 1,
  },
  'src/app/features/budgets/budget-form/budget-form.component.html': {
    'dark:text-gray-200': 1,
    'dark:text-gray-400': 1,
    'dark:text-gray-500': 1,
    'text-gray-400': 1,
    'text-gray-500': 1,
    'text-gray-700': 1,
  },
  'src/app/features/budgets/budget-form/budget-form.component.scss': {
    'border-gray-200': 1,
    'dark:border-gray-700': 1,
  },
  'src/app/features/budgets/budget-progress-card/budget-progress-card.component.scss': {
    'border-gray-100': 1,
    'dark:border-gray-700': 1,
    'dark:text-gray-100': 2,
    'dark:text-gray-400': 1,
    'dark:text-gray-500': 3,
    'dark:text-orange-400': 1,
    'dark:text-red-400': 5,
    'dark:text-yellow-400': 1,
    'text-gray-400': 3,
    'text-gray-500': 1,
    'text-gray-800': 2,
    'text-orange-600': 1,
    'text-red-500': 1,
    'text-red-600': 4,
    'text-yellow-600': 1,
  },
  'src/app/features/budgets/budget-progress-card/budget-progress-card.component.ts': {
    'bg-orange-100': 1,
    'bg-red-100': 1,
    'bg-yellow-100': 2,
    'text-green-600': 1,
    'text-orange-500': 2,
    'text-orange-700': 1,
    'text-red-600': 2,
    'text-red-700': 1,
    'text-yellow-600': 3,
    'text-yellow-700': 2,
  },
  'src/app/features/budgets/goals/goal-form/goal-form.component.html': {
    'dark:text-gray-400': 1,
    'text-gray-500': 1,
  },
  'src/app/features/budgets/goals/goal-progress-card/goal-progress-card.component.scss': {
    'var(--mat-sys-primary, #1976d2)': 1,
  },
  'src/app/features/budgets/recurring-transactions/recurring-transactions.component.scss': {
    'border-gray-100': 1,
    'dark:border-gray-700': 1,
    'dark:text-gray-100': 1,
    'dark:text-gray-400': 4,
    'dark:text-gray-500': 1,
    'text-gray-400': 1,
    'text-gray-500': 3,
    'text-gray-600': 1,
    'text-gray-800': 1,
  },
  'src/app/features/dashboard/spending-chart/spending-chart.component.scss': {
    'white': 1,
  },
  'src/app/features/data/data-management/data-management.component.scss': {
    '#8b5cf6': 2,
    'bg-indigo-50': 2,
    'bg-red-50': 1,
    'bg-white': 1,
    'border-gray-200': 3,
    'border-indigo-200': 3,
    'border-red-200': 1,
    'dark:bg-indigo-900/30': 2,
    'dark:bg-red-900/40': 1,
    'dark:bg-red-950': 1,
    'dark:border-gray-700': 3,
    'dark:border-indigo-600': 2,
    'dark:border-indigo-800': 1,
    'dark:border-red-900': 2,
    'dark:from-indigo-950': 1,
    'dark:text-gray-100': 3,
    'dark:text-gray-300': 4,
    'dark:text-gray-400': 6,
    'dark:text-gray-500': 1,
    'dark:to-purple-950': 1,
    'from-indigo-50': 1,
    'text-gray-400': 1,
    'text-gray-500': 6,
    'text-gray-700': 4,
    'text-gray-800': 3,
    'to-purple-50': 1,
  },
  'src/app/features/reports/category-breakdown/category-breakdown.component.scss': {
    'dark:text-gray-100': 5,
    'dark:text-gray-400': 4,
    'dark:text-gray-500': 2,
    'text-gray-400': 2,
    'text-gray-500': 4,
    'text-gray-800': 5,
  },
  'src/app/features/reports/country-breakdown/country-breakdown.component.scss': {
    'dark:text-gray-100': 2,
    'dark:text-gray-400': 2,
    'dark:text-gray-500': 2,
    'text-gray-400': 2,
    'text-gray-500': 2,
    'text-gray-800': 2,
  },
  'src/app/features/reports/export-dialog/export-dialog.component.scss': {
    'white': 1,
  },
  'src/app/features/reports/forecast/forecast.component.ts': {
    '#22c55e': 1,
    '#6366f1': 1,
    'rgba(34, 197, 94, 0.1)': 1,
    'rgba(99, 102, 241, 0.1)': 1,
  },
  'src/app/features/reports/insights/insight-narrative/insight-narrative.component.scss': {
    'bg-red-50': 1,
    'border-primary-100': 1,
    'dark:bg-red-900/20': 1,
    'dark:border-primary-800': 1,
    'dark:from-primary-900/20': 1,
    'dark:text-red-400': 1,
    'dark:to-indigo-900/20': 1,
    'from-primary-50': 1,
    'text-red-600': 1,
    'to-indigo-50': 1,
  },
  'src/app/features/reports/insights/snapshot-timeline/snapshot-timeline.component.scss': {
    'bg-amber-50': 1,
    'border-amber-200': 1,
    'dark:bg-amber-900/20': 1,
    'dark:border-amber-800': 1,
    'dark:text-amber-400': 1,
    'text-amber-600': 1,
  },
  'src/app/features/reports/monthly-comparison/monthly-comparison.component.scss': {
    'dark:text-gray-400': 1,
    'dark:text-gray-500': 1,
    'text-gray-400': 1,
    'text-gray-500': 1,
  },
  'src/app/features/reports/monthly-comparison/monthly-comparison.component.ts': {
    '#22c55e': 1,
    '#ef4444': 1,
    'rgba(239, 68, 68, 0.35)': 1,
    'rgba(239, 68, 68, 0.5)': 1,
    'rgba(239, 68, 68, 0.8)': 1,
    'rgba(34, 197, 94, 0.35)': 1,
    'rgba(34, 197, 94, 0.5)': 1,
    'rgba(34, 197, 94, 0.8)': 1,
  },
  'src/app/features/reports/recurring-breakdown/recurring-breakdown.component.scss': {
    'dark:text-gray-100': 2,
    'dark:text-gray-400': 1,
    'dark:text-gray-500': 2,
    'text-gray-400': 2,
    'text-gray-500': 1,
    'text-gray-800': 2,
  },
  'src/app/features/reports/spending-analysis/spending-analysis.component.scss': {
    'dark:text-gray-100': 1,
    'dark:text-gray-400': 3,
    'text-gray-500': 3,
    'text-gray-800': 1,
  },
  'src/app/features/reports/spending-analysis/spending-analysis.component.ts': {
    '#22c55e': 1,
    '#6366f1': 1,
    '#ef4444': 1,
    'rgba(239, 68, 68, 0.1)': 1,
    'rgba(34, 197, 94, 0.1)': 1,
    'rgba(99, 102, 241, 0.1)': 1,
  },
  'src/app/features/settings/ai-settings-page/ai-settings-page.component.scss': {
    'rgba(0, 0, 0, 0.3)': 1,
  },
  'src/app/features/settings/category-manager/category-form-dialog/category-form-dialog.component.scss': {
    '#1f2937': 1,
    'bg-indigo-50': 2,
    'border-gray-200': 2,
    'border-indigo-200': 1,
    'dark:bg-indigo-900/30': 2,
    'dark:border-gray-700': 2,
    'dark:border-indigo-600': 1,
    'dark:text-gray-100': 1,
    'dark:text-gray-300': 1,
    'dark:text-gray-400': 1,
    'text-gray-500': 1,
    'text-gray-700': 1,
    'text-gray-800': 1,
    'white': 2,
  },
  'src/app/features/settings/category-manager/category-manager.component.scss': {
    '#ef4444': 2,
    'dark:text-gray-100': 1,
    'dark:text-gray-400': 1,
    'dark:text-gray-500': 1,
    'text-gray-400': 1,
    'text-gray-500': 1,
    'text-gray-800': 1,
  },
  'src/app/features/transactions/insight-chips/insight-chips.component.scss': {
    'border-gray-200': 1,
    'border-gray-300': 1,
    'dark:border-gray-600': 1,
    'dark:border-gray-700': 1,
    'dark:text-gray-400': 1,
    'text-gray-500': 1,
  },
  'src/app/features/transactions/receipt-images/receipt-image-manager.component.scss': {
    'var(--border-primary, rgba(0, 0, 0, 0.06))': 1,
    'var(--border-primary, rgba(0, 0, 0, 0.1))': 1,
    'var(--color-warn, #d32f2f)': 4,
  },
  'src/app/features/transactions/transaction-filters/transaction-filters.component.scss': {
    'border-gray-100': 1,
    'border-gray-200': 2,
    'border-gray-300': 1,
    'dark:border-gray-600': 1,
    'dark:border-gray-700': 3,
    'dark:text-gray-100': 1,
    'dark:text-gray-400': 2,
    'dark:text-gray-500': 3,
    'text-gray-400': 3,
    'text-gray-500': 2,
    'text-gray-900': 1,
    'var(--shadow-lg, 0 4px 16px rgba(0, 0, 0, 0.15))': 1,
    'white': 1,
  },
  'src/app/features/transactions/transaction-form/transaction-form.component.scss': {
    'bg-primary-100': 1,
    'bg-primary-50': 1,
    'border-gray-200': 3,
    'border-gray-300': 2,
    'border-primary-200': 1,
    'dark:bg-primary-900/30': 1,
    'dark:bg-primary-900/50': 1,
    'dark:border-gray-600': 2,
    'dark:border-gray-700': 3,
    'dark:border-primary-700': 1,
    'dark:hover:bg-primary-900/20': 1,
    'dark:text-gray-300': 3,
    'dark:text-gray-400': 3,
    'dark:text-primary-400': 2,
    'dark:text-red-400': 1,
    'hover:bg-primary-50': 1,
    'hover:border-primary-400': 1,
    'text-gray-500': 3,
    'text-gray-600': 2,
    'text-gray-700': 1,
    'text-primary-500': 1,
    'text-primary-600': 2,
    'text-red-600': 1,
  },
  'src/app/features/transactions/transaction-list/transaction-list.component.html': {
    'text-red-500': 4,
  },
  'src/app/features/transactions/transaction-list/transaction-list.component.scss': {
    'border-gray-100': 1,
    'border-gray-200': 1,
    'dark:border-gray-700': 2,
    'dark:text-gray-100': 1,
    'dark:text-gray-300': 1,
    'dark:text-gray-400': 2,
    'dark:text-gray-500': 4,
    'dark:text-primary-400': 2,
    'text-gray-400': 4,
    'text-gray-500': 2,
    'text-gray-700': 1,
    'text-gray-900': 1,
    'text-primary-600': 2,
  },
};

/**
 * A category's own colour, bound in a template or defaulted to a literal.
 * Generated with BASELINE and held the same way.
 */
const BASELINE_CATEGORY = {
  'src/app/core/services/category-helper.service.ts': {
    '#9e9e9e': 2,
  },
  'src/app/features/ai/import/category-suggestion/category-suggestion.component.html': {
    '[style.color]': 2,
  },
  'src/app/features/ai/import/category-suggestion/category-suggestion.component.ts': {
    '#9e9e9e': 1,
  },
  'src/app/features/budgets/budget-form/budget-form.component.html': {
    '[style.color]': 2,
  },
  'src/app/features/budgets/budget-progress-card/budget-progress-card.component.html': {
    '#666': 1,
  },
  'src/app/features/budgets/recurring-transactions/recurring-form-dialog/recurring-form-dialog.component.html': {
    '[style.color]': 1,
  },
  'src/app/features/budgets/recurring-transactions/recurring-transactions.component.html': {
    '[style.background-color]': 1,
    '[style.color]': 1,
  },
  'src/app/features/budgets/recurring-transactions/recurring-transactions.component.ts': {
    '#9e9e9e': 1,
  },
  'src/app/features/dashboard/budget-progress/budget-progress.component.html': {
    '[style.color]': 1,
  },
  'src/app/features/dashboard/spending-chart/spending-chart.component.html': {
    '[style.background-color]': 2,
  },
  'src/app/features/dashboard/spending-chart/spending-chart.component.ts': {
    '#9e9e9e': 2,
  },
  'src/app/features/dashboard/upcoming-bills/upcoming-bills.component.html': {
    '[style.background-color]': 1,
    '[style.color]': 1,
  },
  'src/app/features/household/household-plans/household-budget-dialog/household-budget-dialog.component.html': {
    '[style.color]': 1,
  },
  'src/app/features/reports/category-breakdown/category-breakdown.component.html': {
    '[style.background-color]': 2,
  },
  'src/app/features/reports/category-breakdown/category-breakdown.component.ts': {
    '#9e9e9e': 1,
  },
  'src/app/features/reports/insights/recurring-list/recurring-list.component.ts': {
    '#9e9e9e': 1,
  },
  'src/app/features/reports/spending-analysis/spending-analysis.component.html': {
    '[style.background-color]': 1,
  },
  'src/app/features/reports/spending-analysis/spending-analysis.component.ts': {
    '#9e9e9e': 1,
  },
  'src/app/features/settings/category-manager/category-form-dialog/category-form-dialog.component.html': {
    '[style.background-color]': 2,
    '[style.color]': 2,
  },
  'src/app/features/transactions/transaction-form/split-parts/split-parts.component.html': {
    '[style.color]': 1,
  },
  'src/app/features/transactions/transaction-form/transaction-form.component.html': {
    '[style.color]': 3,
  },
};

/**
 * Colours that are meant to be literal, per file: the kind of marker, how
 * many hits that file's markers exempt, and why.
 */
const ALLOWED = {
  'src/app/core/services/chart-theme.service.ts': {
    kind: 'token-fallback',
    count: 3,
    reason: "a canvas reads computed values; each read falls back to light's token before the stylesheet loads",
  },
  'src/app/core/services/theme.service.ts': {
    kind: 'browser-chrome',
    count: 2,
    reason: 'the theme-color meta takes a literal, the same pair index.html carries',
  },
  'src/app/features/ai/import/import-wizard/import-wizard.component.scss': {
    kind: 'scrim',
    count: 2,
    reason: 'the caption under a receipt thumbnail sits on the photo, which has no theme',
  },
  'src/app/features/auth/login/login.component.html': {
    kind: 'brand',
    count: 4,
    reason: "Google's four-colour mark on the sign-in button",
  },
  'src/app/features/auth/login/login.component.scss': {
    kind: 'brand',
    count: 20,
    reason: "the sign-in page's gradient, glass card and app mark, the same in every theme",
  },
  'src/app/features/settings/ai-settings-page/ai-settings-page.component.scss': {
    kind: 'brand',
    count: 13,
    reason: "each AI provider's own colours on its avatar, in light and a lighter dark step",
  },
  'src/app/features/settings/category-manager/category-form-dialog/category-form-dialog.component.ts': {
    kind: 'category-data',
    count: 16,
    reason: 'the fifteen colours a category can be given, and the one a new category starts with',
  },
  'src/app/features/settings/settings.component.scss': {
    kind: 'brand',
    count: 7,
    reason: "each settings area's colour tile and the white glyph on it",
  },
  'src/app/features/transactions/camera-capture/camera-capture.component.scss': [
    {
      kind: 'brand',
      count: 6,
      reason: "the on-device and cloud scan badges' own gradients",
    },
    {
      kind: 'scrim',
      count: 2,
      reason: 'the drag handle sits on a receipt photo, which has no theme',
    },
  ],
  'src/app/features/transactions/transaction-form/transaction-form.component.scss': {
    kind: 'scrim',
    count: 2,
    reason: 'the scanning veil and its label sit on the receipt photo, which has no theme',
  },
  'src/app/models/category.model.ts': {
    kind: 'category-data',
    count: 21,
    reason: "the seeded categories' colours, each a category's own colour in every theme",
  },
  'src/app/shared/components/category-chip/category-chip.component.ts': {
    kind: 'token-mirror',
    count: 2,
    reason: "CHIP_SURFACE mirrors --surface-card's two values so the chip can composite its tint; its spec holds them to the stylesheet",
  },
};

/** The marker kinds, each a reason a colour may stay literal. */
const KINDS = new Set([
  'brand', // a provider's or the product's own mark, painted the same in every theme
  'scrim', // a fixed dark veil over a photo or a camera feed, which has no theme
  'category-data', // a category's colour as data: the seeded defaults, the picker's palette, a bar of that colour
  'token-mirror', // a TS constant a spec holds to the stylesheet's value
  'token-fallback', // what a canvas reads when the stylesheet has not loaded
  'browser-chrome', // the <meta name="theme-color"> the browser paints its own toolbar with
]);

/** Theme tokens whose declarations in src/styles.scss are the literals' home. */
const TOKEN_PREFIXES = ['--surface-', '--border-', '--text-', '--color-', '--scrollbar-', '--shadow-', '--overlay-'];

/** Custom properties declared by Material rather than by a stylesheet in src. */
const DECLARED_PREFIXES = ['--mat-sys-'];

/** Custom properties set at runtime, so no stylesheet declares them. */
const RUNTIME_DECLARED = {
  '--app-font-scale': 'written on <html> by accessibility.service.ts',
  '--dashboard-areas': 'bound on the grid in dashboard.component.html',
};

/**
 * Tailwind's own palette, and `primary`: the brand ramp tailwind.config.js
 * defines today. It stays listed once the ramp is deleted, when a leftover
 * `text-primary-600` generates nothing and paints whatever it inherits, so
 * the leftover still fails rather than its row going quietly stale. Any other
 * ramp the config defines is added from the config.
 */
const TAILWIND_PALETTE = [
  'slate', 'gray', 'zinc', 'neutral', 'stone', 'red', 'orange', 'amber', 'yellow', 'lime', 'green',
  'emerald', 'teal', 'cyan', 'sky', 'blue', 'indigo', 'violet', 'purple', 'fuchsia', 'pink', 'rose',
  'white', 'black', 'primary',
];

/** The utilities that take a colour. */
const UTILITY_PREFIXES = [
  'text', 'bg', 'border', 'border-x', 'border-y', 'border-t', 'border-r', 'border-b', 'border-l',
  'border-s', 'border-e', 'ring', 'ring-offset', 'divide', 'from', 'via', 'to', 'fill', 'stroke',
  'outline', 'placeholder', 'shadow', 'decoration', 'caret', 'accent',
];

/** CSS Color 4's named colours. */
const NAMED_COLOURS = [
  'aliceblue', 'antiquewhite', 'aqua', 'aquamarine', 'azure', 'beige', 'bisque', 'black',
  'blanchedalmond', 'blue', 'blueviolet', 'brown', 'burlywood', 'cadetblue', 'chartreuse',
  'chocolate', 'coral', 'cornflowerblue', 'cornsilk', 'crimson', 'cyan', 'darkblue', 'darkcyan',
  'darkgoldenrod', 'darkgray', 'darkgreen', 'darkgrey', 'darkkhaki', 'darkmagenta', 'darkolivegreen',
  'darkorange', 'darkorchid', 'darkred', 'darksalmon', 'darkseagreen', 'darkslateblue',
  'darkslategray', 'darkslategrey', 'darkturquoise', 'darkviolet', 'deeppink', 'deepskyblue',
  'dimgray', 'dimgrey', 'dodgerblue', 'firebrick', 'floralwhite', 'forestgreen', 'fuchsia',
  'gainsboro', 'ghostwhite', 'gold', 'goldenrod', 'gray', 'green', 'greenyellow', 'grey', 'honeydew',
  'hotpink', 'indianred', 'indigo', 'ivory', 'khaki', 'lavender', 'lavenderblush', 'lawngreen',
  'lemonchiffon', 'lightblue', 'lightcoral', 'lightcyan', 'lightgoldenrodyellow', 'lightgray',
  'lightgreen', 'lightgrey', 'lightpink', 'lightsalmon', 'lightseagreen', 'lightskyblue',
  'lightslategray', 'lightslategrey', 'lightsteelblue', 'lightyellow', 'lime', 'limegreen', 'linen',
  'magenta', 'maroon', 'mediumaquamarine', 'mediumblue', 'mediumorchid', 'mediumpurple',
  'mediumseagreen', 'mediumslateblue', 'mediumspringgreen', 'mediumturquoise', 'mediumvioletred',
  'midnightblue', 'mintcream', 'mistyrose', 'moccasin', 'navajowhite', 'navy', 'oldlace', 'olive',
  'olivedrab', 'orange', 'orangered', 'orchid', 'palegoldenrod', 'palegreen', 'paleturquoise',
  'palevioletred', 'papayawhip', 'peachpuff', 'peru', 'pink', 'plum', 'powderblue', 'purple',
  'rebeccapurple', 'red', 'rosybrown', 'royalblue', 'saddlebrown', 'salmon', 'sandybrown',
  'seagreen', 'seashell', 'sienna', 'silver', 'skyblue', 'slateblue', 'slategray', 'slategrey',
  'snow', 'springgreen', 'steelblue', 'tan', 'teal', 'thistle', 'tomato', 'turquoise', 'violet',
  'wheat', 'white', 'whitesmoke', 'yellow', 'yellowgreen',
];

/** CSS system colours: right inside forced-colors, a fixed colour anywhere else. */
const SYSTEM_COLOURS = [
  'accentcolor', 'accentcolortext', 'activetext', 'buttonborder', 'buttonface', 'buttontext',
  'canvas', 'canvastext', 'field', 'fieldtext', 'graytext', 'highlight', 'highlighttext',
  'linktext', 'mark', 'marktext', 'selecteditem', 'selecteditemtext', 'visitedtext',
];

/**
 * Properties whose values are identifiers that are not colours — an
 * animation called `snow`, a grid area called `tan`, a font family. A named
 * colour is not looked for in these.
 */
const IDENTIFIER_PROPERTIES = /^(?:animation(?:-name)?|transition(?:-property)?|will-change|grid(?:-[\w-]+)?|font(?:-family|-feature-settings)?|content|counter-(?:reset|increment|set)|list-style(?:-type)?|view-transition-name|container(?:-name)?|quotes|src|mask(?:-image)?)$/i;

/** Colour properties, for the inline styles that live in a template or a TS string. */
const INLINE_COLOUR_DECLARATION = /(?<![\w-])((?:background|border(?:-(?:top|right|bottom|left|inline|block)(?:-(?:start|end))?)?|outline|text-decoration|column-rule)(?:-color)?|color|fill|stroke|box-shadow|text-shadow|caret-color|accent-color|stop-color|flood-color)\s*:\s*([^;{}"'`]*)/gi;

/** Static template attributes whose whole value is a colour. */
const COLOUR_ATTRIBUTES = new Set(['fill', 'stroke', 'color', 'stop-color', 'flood-color', 'lighting-color', 'bgcolor']);

/** Template attributes whose value is a class list. */
const CLASS_ATTRIBUTES = new Set(['class', '[class]', '[ngClass]', '[className]', '[attr.class]']);

/**
 * The binding rule (#461): the properties a category's glyph or tile is bound
 * through, and a bound style object.
 */
const BOUND_COLOUR = /^\[(?:style\.(?:color|background-color|backgroundColor|border-color)|ngStyle)\]$/;

/** A string-literal var() expression, which reads a token and so follows the theme. */
const LITERAL_VAR_EXPRESSION = /^\s*'var\(--[\w-]+\)'\s*$/;

/** The text before a literal that makes it the fallback of a category's colour. */
const CATEGORY_FALLBACK = /color(?:\(\))?\s*(?:\|\||\?\?)\s*$/i;

const HEX = /(?<![\w&#$-])#(?:[0-9a-fA-F]{8}|[0-9a-fA-F]{6}|[0-9a-fA-F]{4}|[0-9a-fA-F]{3})(?![\w-])/g;
const COLOUR_FUNCTION = /(?<![\w-])(?:rgba?|hsla?|hwb|lab|lch|oklab|oklch)\(/gi;
const NAMED = new RegExp(
  `(?<![\\w.#$@%&-])(?:${[...NAMED_COLOURS, ...SYSTEM_COLOURS].sort((a, b) => b.length - a.length).join('|')})(?![\\w(-])`,
  'gi'
);
const SYSTEM = new Set(SYSTEM_COLOURS);

/**
 * The theme's own colour names, from tailwind.config.js: an entry whose value
 * is a var() is an alias that follows the theme, and an entry whose shades
 * are literals is a ramp that does not. Read rather than copied, so a new
 * alias passes and a new ramp fails without an edit here.
 */
function tailwindColours() {
  const config = createRequire(import.meta.url)('../tailwind.config.js');
  const colours = config.theme?.extend?.colors ?? {};
  const aliases = [];
  const ramps = [];
  for (const [name, value] of Object.entries(colours)) {
    if (typeof value === 'string') {
      if (value.startsWith('var(')) aliases.push(name);
      continue;
    }
    const shades = Object.entries(value);
    if (shades.every(([, shade]) => typeof shade === 'string' && shade.startsWith('var('))) {
      for (const [shade] of shades) aliases.push(shade === 'DEFAULT' ? name : `${name}-${shade}`);
    } else {
      ramps.push(name);
    }
  }
  return { aliases, ramps };
}

const alternation = (words) => [...words].sort((a, b) => b.length - a.length).join('|');
const { aliases: ALIASES, ramps: RAMPS } = tailwindColours();
const VARIANTS = '((?:[\\w-]+:)*!?-?)';
const ALPHA = '(?:\\/(?:\\d{1,3}|\\[[^\\]\\s]+\\]))';
const PALETTE_UTILITY = new RegExp(
  `(?<![\\w-])${VARIANTS}(?:${alternation(UTILITY_PREFIXES)})-(?:${alternation(new Set([...TAILWIND_PALETTE, ...RAMPS]))})(?:-\\d{2,3})?${ALPHA}?(?![\\w-])`,
  'g'
);
const ALIAS_ALPHA = new RegExp(
  `(?<![\\w-])${VARIANTS}(?:${alternation(UTILITY_PREFIXES)})-(?:${alternation(ALIASES)})${ALPHA}(?![\\w-])`,
  'g'
);

/**
 * Blanks comments while preserving every byte offset, so a line number taken
 * from the masked text still points at the real line. (Copied from
 * check-direction.mjs, which copied it from check-truncation.mjs — each gate
 * script stays runnable on its own.)
 */
export function maskComments(source) {
  const out = source.split('');
  let i = 0;
  let state = 'code'; // code | line | block | single | double | template
  while (i < source.length) {
    const c = source[i];
    const next = source[i + 1];
    if (state === 'code') {
      if (c === '/' && next === '*') { state = 'block'; out[i] = out[i + 1] = ' '; i += 2; continue; }
      if (c === '/' && next === '/') { state = 'line'; out[i] = out[i + 1] = ' '; i += 2; continue; }
      if (c === "'") state = 'single';
      else if (c === '"') state = 'double';
      else if (c === '`') state = 'template';
    } else if (state === 'block') {
      if (c === '*' && next === '/') { state = 'code'; out[i] = out[i + 1] = ' '; i += 2; continue; }
      if (c !== '\n') out[i] = ' ';
    } else if (state === 'line') {
      if (c === '\n') state = 'code';
      else out[i] = ' ';
    } else if (state === 'single' && c === "'" && source[i - 1] !== '\\') state = 'code';
    else if (state === 'double' && c === '"' && source[i - 1] !== '\\') state = 'code';
    else if (state === 'template' && c === '`' && source[i - 1] !== '\\') state = 'code';
    i += 1;
  }
  return out.join('');
}

/** `<!-- -->` blanked the same way. (Copied from check-direction.mjs.) */
export function maskHtmlComments(source) {
  const out = source.split('');
  let i = 0;
  let inComment = false;
  while (i < source.length) {
    if (!inComment && source.startsWith('<!--', i)) {
      inComment = true;
      for (let k = i; k < i + 4; k += 1) out[k] = ' ';
      i += 4;
      continue;
    }
    if (inComment && source.startsWith('-->', i)) {
      inComment = false;
      for (let k = i; k < i + 3; k += 1) out[k] = ' ';
      i += 3;
      continue;
    }
    if (inComment && source[i] !== '\n') out[i] = ' ';
    i += 1;
  }
  return out.join('');
}

const REGEX_KEYWORDS = new Set([
  'return', 'typeof', 'instanceof', 'in', 'of', 'new', 'delete', 'void', 'throw', 'case', 'do',
  'else', 'yield', 'await',
]);

/**
 * TypeScript, lexed far enough to know what is a string: comments blanked
 * with offsets kept, and the [start, end) of every top-level string literal's
 * contents. Unlike maskComments it knows a regex literal — `/['"]/` would
 * otherwise open a string, and the comment after it would read as code — and
 * a template literal's `${…}`, whose own strings belong to the template.
 */
export function lexTs(source) {
  const out = source.split('');
  const strings = [];
  let i = 0;

  const blank = (from, to) => {
    for (let k = from; k < to; k += 1) if (out[k] !== '\n') out[k] = ' ';
  };

  const regexAllowed = () => {
    let k = i - 1;
    while (k >= 0 && /\s/.test(out[k])) k -= 1;
    if (k < 0) return true;
    if (/[\w$]/.test(out[k])) {
      let s = k;
      while (s > 0 && /[\w$]/.test(out[s - 1])) s -= 1;
      return REGEX_KEYWORDS.has(out.slice(s, k + 1).join(''));
    }
    return !/[)\]'"`]/.test(out[k]);
  };

  const readQuoted = (quote, record) => {
    const start = i + 1;
    i += 1;
    while (i < source.length && source[i] !== quote && source[i] !== '\n') i += source[i] === '\\' ? 2 : 1;
    if (record) strings.push([start, Math.min(i, source.length)]);
    if (source[i] === quote) i += 1;
  };

  const readRegex = () => {
    const start = i;
    let inClass = false;
    i += 1;
    while (i < source.length) {
      const c = source[i];
      if (c === '\n') { i = start + 1; return; } // a division after all
      if (c === '\\') { i += 2; continue; }
      if (c === '[') inClass = true;
      else if (c === ']') inClass = false;
      else if (c === '/' && !inClass) {
        i += 1;
        while (/[a-z]/i.test(source[i] ?? '')) i += 1;
        return;
      }
      i += 1;
    }
  };

  // Declarations, not arrows: a template's `${…}` is code, and code holds templates.
  function readTemplate(record) {
    const start = i + 1;
    i += 1;
    while (i < source.length && source[i] !== '`') {
      if (source[i] === '\\') { i += 2; continue; }
      if (source[i] === '$' && source[i + 1] === '{') { i += 2; readCode(true, false); continue; }
      i += 1;
    }
    if (record) strings.push([start, Math.min(i, source.length)]);
    i += 1;
  }

  function readCode(untilBrace, record) {
    let depth = 0;
    while (i < source.length) {
      const c = source[i];
      const next = source[i + 1];
      if (c === '/' && next === '/') {
        const s = i;
        while (i < source.length && source[i] !== '\n') i += 1;
        blank(s, i);
        continue;
      }
      if (c === '/' && next === '*') {
        const s = i;
        const e = source.indexOf('*/', i + 2);
        i = e === -1 ? source.length : e + 2;
        blank(s, i);
        continue;
      }
      if (c === "'" || c === '"') { readQuoted(c, record); continue; }
      if (c === '`') { readTemplate(record); continue; }
      if (c === '/' && regexAllowed()) { readRegex(); continue; }
      if (untilBrace) {
        if (c === '{') depth += 1;
        else if (c === '}') {
          if (depth === 0) { i += 1; return; }
          depth -= 1;
        }
      }
      i += 1;
    }
  }

  readCode(false, true);
  return { masked: out.join(''), strings };
}

/** The 1-based line of each offset, from a table of line starts. */
function lineIndex(text) {
  const starts = [0];
  for (let i = 0; i < text.length; i += 1) if (text[i] === '\n') starts.push(i + 1);
  return (offset) => {
    let lo = 0;
    let hi = starts.length - 1;
    while (lo < hi) {
      const mid = (lo + hi + 1) >> 1;
      if (starts[mid] <= offset) lo = mid;
      else hi = mid - 1;
    }
    return lo + 1;
  };
}

/** The index just past the `)` that closes the `(` at `open`, quotes respected. */
function closeParen(text, open) {
  let depth = 0;
  for (let i = open; i < text.length; i += 1) {
    const c = text[i];
    if (c === '"' || c === "'") {
      const end = text.indexOf(c, i + 1);
      if (end === -1) return text.length;
      i = end;
    } else if (c === '(') depth += 1;
    else if (c === ')') {
      depth -= 1;
      if (depth === 0) return i + 1;
    }
  }
  return text.length;
}

/** Splits a function's argument text at its top-level commas. */
function topLevelArguments(text) {
  const parts = [];
  let depth = 0;
  let from = 0;
  for (let i = 0; i < text.length; i += 1) {
    if (text[i] === '(') depth += 1;
    else if (text[i] === ')') depth -= 1;
    else if (text[i] === ',' && depth === 0) {
      parts.push(text.slice(from, i));
      from = i + 1;
    }
  }
  parts.push(text.slice(from));
  return parts;
}

/**
 * A token with its case and its spacing around commas and parentheses
 * folded, so a formatter's reformat is not read as a swap. Nothing else is
 * folded: `#fff` and `#ffffff`, or `.5` and `0.5`, stay two tokens, which
 * keeps every baseline key the text a search of the source finds.
 */
function normalise(text) {
  const spaced = text
    .replace(/\s+/g, ' ')
    .replace(/ ?, ?/g, ', ')
    .replace(/\( /g, '(')
    .replace(/ \)/g, ')')
    .trim();
  return /^#|^[a-z]+$/i.test(spaced) || /^[a-z][\w-]*\(/i.test(spaced) ? spaced.toLowerCase() : spaced;
}

/** Ranges of `text` that are quoted strings or url() bodies, where a word is not a colour. */
function quotedRanges(text) {
  const ranges = [];
  const pattern = /'[^']*'|"[^"]*"|url\([^)]*\)/gi;
  let match;
  while ((match = pattern.exec(text)) !== null) ranges.push([match.index, match.index + match[0].length]);
  return ranges;
}

const inside = (ranges, at) => ranges.some(([from, to]) => at >= from && at < to);

/** Every palette utility, and every alias given an alpha it cannot take, in `text`. */
function paletteHits(text, offset) {
  const hits = [];
  for (const [pattern, rule] of [[PALETTE_UTILITY, 'palette'], [ALIAS_ALPHA, 'alias-alpha']]) {
    pattern.lastIndex = 0;
    let match;
    while ((match = pattern.exec(text)) !== null) {
      hits.push({ start: offset + match.index, end: offset + match.index + match[0].length, token: match[0], rule });
    }
  }
  return hits;
}

/** Hex and functional colours in `text`; a hex inside an `rgba()` is that call. */
function literalHits(text, offset, skip = []) {
  const hits = [];
  const taken = [...skip];
  COLOUR_FUNCTION.lastIndex = 0;
  let match;
  while ((match = COLOUR_FUNCTION.exec(text)) !== null) {
    if (inside(taken, match.index)) continue;
    const end = closeParen(text, match.index + match[0].length - 1);
    hits.push({ start: offset + match.index, end: offset + end, token: normalise(text.slice(match.index, end)), rule: 'literal' });
    taken.push([match.index, end]);
  }
  HEX.lastIndex = 0;
  while ((match = HEX.exec(text)) !== null) {
    if (inside(taken, match.index)) continue;
    hits.push({ start: offset + match.index, end: offset + match.index + match[0].length, token: normalise(match[0]), rule: 'literal' });
  }
  return hits;
}

/** Named colours in a value, outside strings and url(); system colours pass inside forced-colors. */
function namedHits(text, offset, { forced = false } = {}) {
  const hits = [];
  const quoted = quotedRanges(text);
  NAMED.lastIndex = 0;
  let match;
  while ((match = NAMED.exec(text)) !== null) {
    if (inside(quoted, match.index)) continue;
    const token = match[0].toLowerCase();
    if (forced && SYSTEM.has(token)) continue;
    hits.push({ start: offset + match.index, end: offset + match.index + match[0].length, token, rule: 'literal' });
  }
  return hits;
}

/**
 * Named colours inside Tailwind's arbitrary values, `text-[red]`, in a class
 * list or an `@apply`. Anywhere else in a class list a word like `red` is
 * part of a utility's name, not a colour.
 */
function arbitraryNamedHits(text, offset) {
  const hits = [];
  for (const match of text.matchAll(/-\[([^\]\s]+)\]/g)) hits.push(...namedHits(match[1], offset + match.index + 2));
  return hits;
}

/** Named colours in the colour properties of an inline style. */
function inlineStyleHits(text, offset) {
  const hits = [];
  INLINE_COLOUR_DECLARATION.lastIndex = 0;
  let match;
  while ((match = INLINE_COLOUR_DECLARATION.exec(text)) !== null) {
    const valueAt = match.index + match[0].length - match[2].length;
    hits.push(...namedHits(match[2], offset + valueAt));
  }
  return hits;
}

/** Whether a fallback or an operand carries a colour of its own. */
function hasColourLiteral(text) {
  return literalHits(text, 0).length > 0 || namedHits(text, 0).length > 0;
}

/** Whether a custom property is declared somewhere the cascade can see it. */
function isDeclared(name, declared) {
  return (
    declared.has(name) ||
    Object.hasOwn(RUNTIME_DECLARED, name) ||
    DECLARED_PREFIXES.some((prefix) => name.startsWith(prefix))
  );
}

let treeDeclaredCache = null;

/** Every custom property declared in a stylesheet under src. */
function treeDeclared() {
  if (treeDeclaredCache) return treeDeclaredCache;
  const declared = new Set();
  for (const file of walk(STYLESHEET_ROOT, ['.scss'])) {
    const masked = maskComments(readFileSync(file, 'utf8'));
    for (const match of masked.matchAll(/(?<![\w-])(--[\w-]+)\s*:/g)) declared.add(match[1]);
  }
  treeDeclaredCache = declared;
  return declared;
}

/**
 * A stylesheet value: var() fallbacks, color-mix() operands, literals and
 * named colours, each hit once. A fallback or a mix that is a hit covers
 * the literals inside it.
 */
function valueHits(value, offset, { declared, named, forced }) {
  const hits = [];
  const covered = [];

  for (const match of value.matchAll(/var\(\s*(--[\w-]+)\s*,/g)) {
    if (inside(covered, match.index)) continue;
    const end = closeParen(value, match.index + 3);
    const fallback = value.slice(match.index + match[0].length, end - 1);
    if (!hasColourLiteral(fallback)) continue;
    hits.push({
      start: offset + match.index,
      end: offset + end,
      token: normalise(value.slice(match.index, end)),
      rule: isDeclared(match[1], declared) ? 'dead-fallback' : 'undeclared-fallback',
    });
    covered.push([match.index, end]);
  }

  for (const match of value.matchAll(/color-mix\(/gi)) {
    if (inside(covered, match.index)) continue;
    const end = closeParen(value, match.index + match[0].length - 1);
    const operands = topLevelArguments(value.slice(match.index + match[0].length, end - 1)).slice(1);
    const bad = operands.some((operand) => {
      const colour = operand.replace(/(?<![\w-])\d+(?:\.\d+)?%/g, '').trim();
      if (/^(?:transparent|currentcolor)$/i.test(colour)) return false;
      const plainVar = colour.match(/^var\(\s*(--[\w-]+)\s*(?:,[\s\S]*)?\)$/);
      if (plainVar) return !isDeclared(plainVar[1], declared) && !hasColourLiteral(colour);
      if (/^color-mix\(/i.test(colour)) return false; // judged on its own
      return !hasColourLiteral(colour); // a literal is its own hit
    });
    if (!bad) continue;
    hits.push({ start: offset + match.index, end: offset + end, token: normalise(value.slice(match.index, end)), rule: 'color-mix' });
    covered.push([match.index, end]);
  }

  const quoted = quotedRanges(value);
  hits.push(...literalHits(value, offset, [...covered, ...quoted]));
  if (named) {
    hits.push(...namedHits(value, offset, { forced }).filter((hit) => !inside(covered, hit.start - offset)));
  }
  hits.push(...paletteHits(value, offset));
  return hits;
}

/**
 * A stylesheet cut into statements: each prelude (ending in `{`) and each
 * declaration or at-statement (ending in `;` or `}`), with the block it sits
 * in. `#{…}` interpolation and parentheses do not cut.
 */
function statements(masked) {
  const out = [];
  const stack = [0];
  let nextBlock = 1;
  let start = 0;
  let paren = 0;
  const push = (end, terminator) => {
    const raw = masked.slice(start, end);
    const text = raw.trim();
    if (text) {
      out.push({ start: start + (raw.length - raw.trimStart().length), text, block: stack.at(-1), terminator, opens: terminator === '{' ? nextBlock : null });
    }
  };
  for (let i = 0; i < masked.length; i += 1) {
    const c = masked[i];
    if (c === '"' || c === "'") {
      const end = masked.indexOf(c, i + 1);
      i = end === -1 ? masked.length : end;
    } else if (c === '#' && masked[i + 1] === '{') {
      const end = masked.indexOf('}', i);
      i = end === -1 ? masked.length : end;
    } else if (c === '(') paren += 1;
    else if (c === ')') paren = Math.max(0, paren - 1);
    else if (paren === 0 && c === '{') {
      push(i, '{');
      stack.push(nextBlock);
      nextBlock += 1;
      start = i + 1;
    } else if (paren === 0 && (c === ';' || c === '}')) {
      push(i, c);
      if (c === '}' && stack.length > 1) stack.pop();
      start = i + 1;
    }
  }
  push(masked.length, '');
  return out;
}

/**
 * Every hit in a stylesheet, before markers. `global` is src/styles.scss,
 * where the theme tokens' own declarations are exempt.
 */
export function scanScss(source, { global = false, declared = treeDeclared() } = {}) {
  const masked = maskComments(source);
  const lineAt = lineIndex(masked);
  const forcedBlocks = new Set();
  const byBlock = new Map();
  const hits = [];

  for (const statement of statements(masked)) {
    if (statement.terminator === '{') {
      if (forcedBlocks.has(statement.block) || /^@media[^{]*forced-colors/.test(statement.text)) {
        forcedBlocks.add(statement.opens);
      }
      continue;
    }
    const forced = forcedBlocks.has(statement.block);
    const found = [];
    let property = null;
    let value = null;
    if (statement.text.startsWith('@apply')) {
      found.push(...paletteHits(statement.text, statement.start));
      found.push(...literalHits(statement.text, statement.start));
      found.push(...arbitraryNamedHits(statement.text, statement.start));
    } else if (/^@(?:use|forward|import)\b/.test(statement.text)) {
      continue;
    } else if (statement.text.startsWith('@')) {
      found.push(...literalHits(statement.text, statement.start, quotedRanges(statement.text)));
    } else {
      const colon = statement.text.indexOf(':');
      if (colon === -1) continue;
      property = statement.text.slice(0, colon).trim();
      value = statement.text.slice(colon + 1);
      if (global && TOKEN_PREFIXES.some((prefix) => property.startsWith(prefix))) continue;
      const named = /^(?:--|\$)?[a-zA-Z][\w-]*$/.test(property) && !IDENTIFIER_PROPERTIES.test(property);
      found.push(...valueHits(value, statement.start + colon + 1, { declared, named, forced }));
      if (/^--(?:mat|mdc)-/.test(property)) {
        for (const hit of found) if (hit.rule === 'literal') hit.rule = 'material-token';
      }
    }
    if (!byBlock.has(statement.block)) byBlock.set(statement.block, []);
    byBlock.get(statement.block).push({ property, value, found });
    hits.push(...found);
  }

  // White on a fill that is a token: --text-inverse is the token that turns
  // with it.
  for (const declarations of byBlock.values()) {
    const tokenFill = declarations.some(
      (d) => /^background(?:-color)?$/.test(d.property ?? '') && /var\(--/.test(d.value)
    );
    if (!tokenFill) continue;
    for (const d of declarations) {
      if (d.property !== 'color') continue;
      for (const hit of d.found) if (['white', '#fff', '#ffffff'].includes(hit.token)) hit.rule = 'white-on-token-fill';
    }
  }

  return hits
    .sort((a, b) => a.start - b.start)
    .map((hit) => ({ line: lineAt(hit.start), token: hit.token, rule: hit.rule, category: false }));
}

/** Whether the quoted string holding [from, to) in `text` is the fallback of a colour read. */
function categoryFallback(text, from, to) {
  const quote = text[from - 1];
  if (quote !== "'" && quote !== '"' && quote !== '`') return false;
  if (text[to] !== quote) return false;
  return CATEGORY_FALLBACK.test(text.slice(Math.max(0, from - 120), from - 1));
}

/**
 * Hits in markup — a template file, or an inline template inside a TS
 * string. `literals` is false for the inline case, where the whole string
 * has already been read for literals and utilities.
 */
function markupHits(text, offset, { file, literals }) {
  const hits = [];
  const attribute = /(?<=[\s<])([^\s"'<>/=]+)\s*=\s*(?:"([^"]*)"|'([^']*)')/g;
  let match;
  while ((match = attribute.exec(text)) !== null) {
    const name = match[1];
    const value = match[2] ?? match[3];
    const valueAt = match.index + match[0].length - value.length - 1;
    const bound = name.startsWith('[');

    if (BOUND_COLOUR.test(name) && file !== CHIP_FILE && !LITERAL_VAR_EXPRESSION.test(value)) {
      hits.push({ start: offset + match.index, token: name, rule: 'binding', category: true });
    }
    if (bound) {
      for (const quoted of value.matchAll(/'([^']*)'/g)) {
        const inner = quoted[1].trim().toLowerCase();
        if (NAMED_COLOURS.includes(inner)) {
          hits.push({ start: offset + valueAt + quoted.index + 1, token: inner, rule: 'literal', category: false });
        }
      }
    } else if (COLOUR_ATTRIBUTES.has(name.toLowerCase()) && NAMED_COLOURS.includes(value.trim().toLowerCase())) {
      hits.push({ start: offset + valueAt, token: value.trim().toLowerCase(), rule: 'literal', category: false });
    }
    if (!literals) continue;

    if (CLASS_ATTRIBUTES.has(name)) hits.push(...paletteHits(value, offset + valueAt));
    const classBinding = name.match(/^\[class\.(.+)\]$/);
    if (classBinding) hits.push(...paletteHits(classBinding[1], offset + match.index + 7));
    if (name === 'style') hits.push(...inlineStyleHits(value, offset + valueAt));
    for (const hit of literalHits(value, offset + valueAt)) {
      const from = hit.start - offset - valueAt;
      hits.push({ ...hit, category: categoryFallback(value, from, hit.end - offset - valueAt) });
    }
  }
  if (literals) {
    for (const interpolation of text.matchAll(/\{\{([\s\S]*?)\}\}/g)) {
      hits.push(...literalHits(interpolation[1], offset + interpolation.index + 2));
    }
  }
  return hits;
}

/** Every hit in a template, before markers. */
export function scanHtml(source, { file = '' } = {}) {
  const masked = maskHtmlComments(source);
  const lineAt = lineIndex(masked);
  return markupHits(masked, 0, { file, literals: true })
    .sort((a, b) => a.start - b.start)
    .map((hit) => ({ line: lineAt(hit.start), token: hit.token, rule: hit.rule, category: hit.category ?? false }));
}

/** Every hit in TypeScript, before markers: any string's utilities and literals, and an inline template's bindings. */
export function scanTs(source, { file = '' } = {}) {
  const { masked, strings } = lexTs(source);
  const lineAt = lineIndex(masked);
  const hits = [];
  for (const [start, end] of strings) {
    const text = source.slice(start, end);
    hits.push(...paletteHits(text, start).map((hit) => ({ ...hit, category: false })));
    for (const hit of literalHits(text, start)) {
      hits.push({ ...hit, category: categoryFallback(masked, hit.start, hit.end) });
    }
    const whole = text.trim().toLowerCase();
    if (NAMED_COLOURS.includes(whole)) hits.push({ start, token: whole, rule: 'literal', category: false });
    hits.push(...inlineStyleHits(text, start).map((hit) => ({ ...hit, category: false })));
    if (text.includes('<')) hits.push(...markupHits(text, start, { file, literals: false }));
  }
  return hits
    .sort((a, b) => a.start - b.start)
    .map((hit) => ({ line: lineAt(hit.start), token: hit.token, rule: hit.rule, category: hit.category ?? false }));
}

const MARKER = /colors:allow(?:-(start|end))?(?:\(([^)]*)\))?(.*)$/;

/**
 * The column of the first marker on a line that sits in a comment, or -1.
 * The masker keeps every byte outside a comment, so a marker it blanked is a
 * comment and one it kept is a string or an attribute value.
 */
function markerColumn(rawLine, maskedLine) {
  for (let at = rawLine.indexOf('colors:allow'); at !== -1; at = rawLine.indexOf('colors:allow', at + 1)) {
    if (maskedLine[at] === ' ') return at;
  }
  return -1;
}

/** The line its `>` closes on, for a tag opening on line `index` (0-based), or null. */
function tagEnd(maskedLines, index) {
  let k = index;
  while (k < maskedLines.length && maskedLines[k].trim() === '') k += 1;
  if (k >= maskedLines.length || !/^\s*<[a-zA-Z]/.test(maskedLines[k])) return null;
  let quote = null;
  for (let line = k; line < maskedLines.length; line += 1) {
    const text = maskedLines[line];
    for (let i = line === k ? text.indexOf('<') + 1 : 0; i < text.length; i += 1) {
      const c = text[i];
      if (quote) {
        if (c === quote) quote = null;
      } else if (c === '"' || c === "'") quote = c;
      else if (c === '>') return line + 1;
    }
  }
  return null;
}

/**
 * The markers in a file's comments, read from the raw text, as 1-based line
 * ranges with their kind and reason, and every marker that is malformed.
 */
export function parseMarkers(raw, masked, flavour) {
  const rawLines = raw.split('\n');
  const maskedLines = masked.split('\n');
  const markers = [];
  const errors = [];
  let open = null;

  rawLines.forEach((line, index) => {
    const column = markerColumn(line, maskedLines[index] ?? '');
    if (column === -1) return;
    const match = line.slice(column).match(MARKER);
    const at = index + 1;
    const [, edge, kindText, rest] = match;
    if (edge === 'end') {
      if (open === null) errors.push(`line ${at}: colors:allow-end with no colors:allow-start before it`);
      else markers.push({ ...open, to: at });
      open = null;
      return;
    }
    const kind = (kindText ?? '').trim();
    const spelled = `colors:allow${edge ? `-${edge}` : ''}(${kind})`;
    const reason = (rest ?? '').replace(/\*\/.*$/, '').replace(/-->.*$/, '').trim();
    if (!KINDS.has(kind)) {
      errors.push(`line ${at}: ${spelled} — the kind must be one of ${[...KINDS].join(', ')}`);
      return;
    }
    if (reason === '') {
      errors.push(`line ${at}: ${spelled} gives no reason`);
      return;
    }
    if (edge === 'start') {
      if (open !== null) errors.push(`line ${at}: ${spelled} opens inside the block opened on line ${open.from}`);
      open = { kind, reason, from: at };
      return;
    }
    const tagLine = flavour === 'html' && maskedLines[index].trim() === '' ? tagEnd(maskedLines, index + 1) : null;
    markers.push({ kind, reason, from: at, to: tagLine ?? at });
  });

  if (open !== null) errors.push(`line ${open.from}: colors:allow-start(${open.kind}) is never closed by colors:allow-end`);
  return { markers, errors };
}

/**
 * One file's verdict: the hits no marker exempts, how many each kind of
 * marker exempts, and every malformed or idle marker.
 */
export function review(flavour, source, { file = '', declared = undefined, global = false } = {}) {
  let hits;
  let masked;
  if (flavour === 'scss') {
    hits = scanScss(source, { global, declared: declared ?? treeDeclared() });
    masked = maskComments(source);
  } else if (flavour === 'html') {
    hits = scanHtml(source, { file });
    masked = maskHtmlComments(source);
  } else {
    hits = scanTs(source, { file });
    masked = lexTs(source).masked;
  }

  const { markers, errors } = parseMarkers(source, masked, flavour);
  const used = new Set();
  const kept = [];
  const exempted = {};
  for (const hit of hits) {
    const marker = markers.find((m) => hit.line >= m.from && hit.line <= m.to);
    if (marker === undefined) {
      kept.push(hit);
      continue;
    }
    used.add(marker);
    exempted[marker.kind] = (exempted[marker.kind] ?? 0) + 1;
  }
  for (const marker of markers) {
    if (!used.has(marker)) errors.push(`line ${marker.from}: colors:allow(${marker.kind}) exempts nothing — remove it`);
  }
  return { kept, exempted, errors };
}

/**
 * Where a file's counts part from its baseline: each token above it (or not
 * in it at all) and each below it, as [token, actual, frozen].
 */
export function tokenDrift(actual, frozen = {}) {
  const over = [];
  const under = [];
  for (const token of Object.keys(actual).sort()) {
    if (actual[token] > (frozen[token] ?? 0)) over.push([token, actual[token], frozen[token] ?? 0]);
  }
  for (const token of Object.keys(frozen).sort()) {
    if ((actual[token] ?? 0) < frozen[token]) under.push([token, actual[token] ?? 0, frozen[token]]);
  }
  return { over, under };
}

/** A row in ALLOWED: a known kind, a positive hit count and a non-empty reason. */
export function allowedRowValid(row) {
  return (
    row !== null &&
    typeof row === 'object' &&
    KINDS.has(row.kind) &&
    Number.isInteger(row.count) &&
    row.count > 0 &&
    typeof row.reason === 'string' &&
    row.reason.trim().length > 0
  );
}

/** A file's ALLOWED entry as rows: one row, or an array when the file marks more than one kind. */
function rowsOf(entry) {
  if (entry === undefined) return [];
  return Array.isArray(entry) ? entry : [entry];
}

/**
 * Where a file's markers part from its ALLOWED entry, in either direction: a
 * kind with no row, a row whose count is above or below what its markers
 * exempt (a row for markers that are gone included), or a malformed row.
 */
export function allowedDrift(exempted, entry) {
  const problems = [];
  const kinds = new Set();
  for (const row of rowsOf(entry)) {
    if (!allowedRowValid(row)) {
      problems.push('an ALLOWED row needs a known kind, a positive count and a reason');
      continue;
    }
    if (kinds.has(row.kind)) {
      problems.push(`ALLOWED has two ${row.kind} rows; one row per kind`);
      continue;
    }
    kinds.add(row.kind);
    const count = exempted[row.kind] ?? 0;
    if (count !== row.count) {
      problems.push(`${row.kind} markers exempt ${count} hit(s) but ALLOWED says ${row.count}; edit the row to match`);
    }
  }
  for (const kind of Object.keys(exempted).sort()) {
    if (!kinds.has(kind) && !rowsOf(entry).some((row) => row?.kind === kind)) {
      problems.push(`${kind} markers exempt ${exempted[kind]} hit(s) but ALLOWED has no ${kind} row for the file`);
    }
  }
  return problems;
}

function walk(dir, extensions, found = []) {
  for (const entry of readdirSync(dir)) {
    if (SKIP_DIRS.has(entry)) continue;
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) walk(path, extensions, found);
    else if (extensions.some((ext) => entry.endsWith(ext)) && !entry.endsWith('.spec.ts')) found.push(path);
  }
  return found;
}

function posix(path) {
  return path.split(sep).join('/');
}

function flavourOf(file) {
  if (file.endsWith('.scss')) return 'scss';
  if (file.endsWith('.html')) return 'html';
  return 'ts';
}

/** Every file in scope, reviewed, keyed by repo-relative path. */
function collect() {
  const files = [GLOBAL_STYLESHEET, ...walk(SOURCE_DIR, ['.scss', '.html', '.ts']).map(posix)];
  const declared = treeDeclared();
  const reviewed = new Map();
  for (const file of files) {
    const verdict = review(flavourOf(file), readFileSync(file, 'utf8'), {
      file,
      declared,
      global: file === GLOBAL_STYLESHEET,
    });
    const counts = { main: {}, category: {} };
    for (const hit of verdict.kept) {
      const table = hit.category ? counts.category : counts.main;
      table[hit.token] = (table[hit.token] ?? 0) + 1;
    }
    reviewed.set(file, { ...verdict, counts });
  }
  return { files, reviewed };
}

/** A key or token, single-quoted for pasting into this file. */
function quote(text) {
  return `'${text.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function printTable(name, files) {
  console.log(`const ${name} = {`);
  for (const [file, counts] of files) {
    console.log(`  ${quote(file)}: {`);
    for (const token of Object.keys(counts).sort()) console.log(`    ${quote(token)}: ${counts[token]},`);
    console.log('  },');
  }
  console.log('};');
}

function printBaseline() {
  const { reviewed } = collect();
  const paths = [...reviewed.keys()].sort();
  const main = paths.filter((p) => Object.keys(reviewed.get(p).counts.main).length > 0);
  const category = paths.filter((p) => Object.keys(reviewed.get(p).counts.category).length > 0);
  printTable('BASELINE', main.map((p) => [p, reviewed.get(p).counts.main]));
  console.log('');
  printTable('BASELINE_CATEGORY', category.map((p) => [p, reviewed.get(p).counts.category]));

  const sum = (rows, table) =>
    rows.reduce((total, p) => total + Object.values(reviewed.get(p).counts[table]).reduce((a, b) => a + b, 0), 0);
  console.error(`\nBASELINE: ${main.length} file(s), ${sum(main, 'main')} hit(s).`);
  console.error(`BASELINE_CATEGORY: ${category.length} file(s), ${sum(category, 'category')} hit(s).`);
  const marked = paths.filter((p) => Object.keys(reviewed.get(p).exempted).length > 0);
  if (marked.length > 0) {
    console.error('Marker counts ALLOWED must match (each row also needs a reason):');
    for (const p of marked) {
      for (const [kind, count] of Object.entries(reviewed.get(p).exempted)) console.error(`  ${p}  ${kind}: ${count}`);
    }
  }
}

function sumOf(counts) {
  return Object.values(counts).reduce((a, b) => a + b, 0);
}

function describe(hit, file) {
  return `    ${file}:${hit.line}  ${hit.token}  (${hit.rule})`;
}

const ADVICE = {
  palette: 'a palette utility paints the same in every theme — use a theme alias (text-fg-muted, bg-surface-card, border-line, …)',
  'alias-alpha': 'an alias takes no /alpha — Tailwind generates nothing; mix it in the stylesheet with color-mix()',
  literal: 'read a token from src/styles.scss instead',
  'material-token': 'give the Material token a var() of a theme token',
  'white-on-token-fill': 'white on a token fill — use --text-inverse, which turns with the fill',
  'dead-fallback': 'the token is declared, so the fallback never paints — drop it',
  'undeclared-fallback': 'the token is declared nowhere, so the fallback always paints — use a declared token',
  'color-mix': 'every color-mix() operand must be a declared var(), transparent or currentColor',
  binding: 'a bound colour bypasses every stylesheet — draw a category colour through the chip',
};

function run() {
  const { files, reviewed } = collect();
  const problems = [];

  const checkTable = (name, frozenTable, pick) => {
    for (const [file, verdict] of [...reviewed.entries()].sort()) {
      const actual = verdict.counts[pick];
      const frozen = frozenTable[file];
      const { over, under } = tokenDrift(actual, frozen);
      if (over.length > 0) {
        const tokens = new Set(over.map(([token]) => token));
        const lines = verdict.kept.filter((hit) => (pick === 'category') === hit.category && tokens.has(hit.token));
        problems.push(
          `${file} — ${over.map(([t, a, f]) => `${t} ×${a} (${name} ${f})`).join(', ')}:\n` +
            lines.map((hit) => `${describe(hit, file)}\n      ${ADVICE[hit.rule]}`).join('\n')
        );
      }
      if (under.length > 0) {
        problems.push(
          `${file} — ${under.map(([t, a, f]) => `${t} ×${a}`).join(', ')} but ${name} still says ` +
            `${under.map(([t, , f]) => `${t} ×${f}`).join(', ')}; the ratchet is stale — lower or remove the entry.`
        );
      }
    }
    for (const file of Object.keys(frozenTable).sort()) {
      if (reviewed.has(file)) continue;
      problems.push(`${file} — ${name} lists ${sumOf(frozenTable[file])} hit(s) but the file is ${existsSync(file) ? 'out of scope' : 'gone'}; remove the entry.`);
    }
  };
  checkTable('BASELINE', BASELINE, 'main');
  checkTable('BASELINE_CATEGORY', BASELINE_CATEGORY, 'category');

  for (const [file, verdict] of [...reviewed.entries()].sort()) {
    for (const error of verdict.errors) problems.push(`${file} — ${error}`);
    for (const drift of allowedDrift(verdict.exempted, ALLOWED[file])) problems.push(`${file} — ${drift}.`);
  }
  for (const file of Object.keys(ALLOWED).sort()) {
    if (!reviewed.has(file)) problems.push(`${file} — ALLOWED has a row but the file is ${existsSync(file) ? 'out of scope' : 'gone'}.`);
  }

  const counts = { scss: 0, html: 0, ts: 0 };
  for (const file of files) counts[flavourOf(file)] += 1;
  console.log(
    `Checked ${counts.scss} stylesheets, ${counts.html} templates and ${counts.ts} TypeScript sources for colours outside the theme tokens.`
  );

  if (problems.length > 0) {
    console.error(`\n${problems.length} colour problem(s):\n`);
    for (const problem of problems) console.error(`  ${problem}\n`);
    console.error(
      `A colour outside the tokens in src/styles.scss paints the same in light, dark and high\n` +
        `contrast. BASELINE and BASELINE_CATEGORY in scripts/check-colors.mjs freeze the ones\n` +
        `already here and may only shrink; a slice that clears a hit lowers or removes its\n` +
        `row in the same commit. A colour that is meant to be literal is marked where it\n` +
        `stands, colors:allow(<kind>) <reason>, and counted in ALLOWED; a marker that is\n` +
        `added, removed or widened edits its file's row in the same commit.\n` +
        `\`node scripts/check-colors.mjs --print-baseline\` prints the tables for the current\n` +
        `tree. Reference: ${DOC}.\n`
    );
    process.exit(1);
  }

  const frozen = (table) => Object.values(table).reduce((total, row) => total + sumOf(row), 0);
  const allowed = Object.values(ALLOWED).flatMap(rowsOf).reduce((total, row) => total + row.count, 0);
  console.log(
    `Colours are where the baselines say: ${frozen(BASELINE)} frozen in ${Object.keys(BASELINE).length} file(s), ` +
      `${frozen(BASELINE_CATEGORY)} category hit(s) in ${Object.keys(BASELINE_CATEGORY).length}, ` +
      `${allowed} marked in ${Object.keys(ALLOWED).length}.`
  );
}

function selfTest() {
  const results = [];
  const check = (name, actual, expected) => {
    results.push({
      name,
      ok: JSON.stringify(actual) === JSON.stringify(expected),
      actual,
      expected,
    });
  };

  // A fixed declared set, so the fixtures do not depend on the tree's
  // stylesheets. `--mat-sys-*` and the runtime names are declared by rule.
  const declared = new Set([
    '--text-primary',
    '--text-muted',
    '--border-primary',
    '--color-primary',
    '--color-error',
    '--surface-card',
  ]);
  const kept = (flavour, source, options = {}) =>
    review(flavour, source, { declared, ...options }).kept;
  const tokens = (flavour, source, options) => kept(flavour, source, options).map((hit) => hit.token);
  const rules = (flavour, source, options) => kept(flavour, source, options).map((hit) => hit.rule);
  const scss = (source, options) => tokens('scss', source, options);
  const html = (source, options) => tokens('html', source, options);
  const ts = (source, options) => tokens('ts', source, options);

  // --- must hit -----------------------------------------------------------
  check('a hex colour', scss('.a { color: #abc; }'), ['#abc']);
  check('a functional colour', scss('.a { background: rgba(0, 0, 0, 0.5); }'), ['rgba(0, 0, 0, 0.5)']);
  check('a named colour', scss('.a { border-color: red; }'), ['red']);
  check(
    'white on a token fill',
    rules('scss', '.a {\n  background: var(--color-primary);\n  color: white;\n}'),
    ['white-on-token-fill']
  );
  check(
    'a fallback for an undeclared token always renders',
    kept('scss', '.a { color: var(--color-warn, #d32f2f); }').map((hit) => [hit.rule, hit.token]),
    [['undeclared-fallback', 'var(--color-warn, #d32f2f)']]
  );
  check(
    'a fallback for a declared token is dead',
    kept('scss', '.a { color: var(--text-muted, #666); }').map((hit) => [hit.rule, hit.token]),
    [['dead-fallback', 'var(--text-muted, #666)']]
  );
  check('palette utilities inside @apply', scss('.a { @apply text-gray-500 dark:text-gray-400; }'), [
    'text-gray-500',
    'dark:text-gray-400',
  ]);
  check('a palette utility named by a class binding', html('<div [class.dark:bg-red-900]="on"></div>'), [
    'dark:bg-red-900',
  ]);
  check('a palette utility in a class attribute', html('<p class="mb-1 text-gray-600">x</p>'), ['text-gray-600']);
  check('a palette utility in [ngClass]', html(`<p [ngClass]="{ 'text-red-500': bad }">x</p>`), ['text-red-500']);
  check('a brand-ramp utility', html('<p class="text-primary-600 dark:bg-primary-900/50">x</p>'), [
    'text-primary-600',
    'dark:bg-primary-900/50',
  ]);
  check('a palette utility in a TypeScript string', ts("function f() { return 'text-red-600 font-semibold'; }"), [
    'text-red-600',
  ]);
  check('a Tailwind arbitrary colour', html('<div class="bg-[#fff]"></div>'), ['#fff']);
  check('an arbitrary hex inside @apply', scss('.a { @apply bg-[#123456]; }'), ['#123456']);
  check('an arbitrary functional colour inside @apply', scss('.a { @apply text-[rgb(1,2,3)]; }'), ['rgb(1, 2, 3)']);
  check('an arbitrary named colour inside @apply', scss('.a { @apply text-[red]; }'), ['red']);
  check('an alias given an alpha it cannot take', html('<div class="bg-brand/12"></div>'), ['bg-brand/12']);
  check('an alias given an alpha inside @apply', scss('.a { @apply bg-error/10; }'), ['bg-error/10']);
  check('a colour literal in a binding', html(`<mat-icon [color]="x || '#666'"></mat-icon>`), ['#666']);
  check('a bound background colour', html('<div [style.background-color]="c"></div>'), ['[style.background-color]']);
  check('a bound colour', html('<mat-icon [style.color]="c"></mat-icon>'), ['[style.color]']);
  check('a bound style object', html('<div [ngStyle]="styles"></div>'), ['[ngStyle]']);
  check('a Material token given a literal', scss('.dark-theme {\n  --mdc-x-color: #111;\n}'), ['#111']);
  check(
    'a Material token given a literal in the global stylesheet',
    rules('scss', '.dark-theme {\n  --mdc-x-color: #111;\n}', { global: true }),
    ['material-token']
  );
  check(
    'a color-mix() over an undeclared token',
    scss('.a { background: color-mix(in srgb, var(--color-warn) 10%, transparent); }'),
    ['color-mix(in srgb, var(--color-warn) 10%, transparent)']
  );
  check(
    'a flagged color-mix() is one hit, literals and all',
    scss('.a { border-color: color-mix(in srgb, var(--color-warn) 30%, white); }'),
    ['color-mix(in srgb, var(--color-warn) 30%, white)']
  );
  // `#{` must not open a block, or the statement it ends is read as a selector.
  check('a palette utility before an interpolated !important', scss('.a { @apply text-gray-500 #{!important}; }'), [
    'text-gray-500',
  ]);
  check(
    'a color-mix() over a literal is the literal',
    scss('.a { background: color-mix(in srgb, #3f51b5 10%, var(--surface-card)); }'),
    ['#3f51b5']
  );
  check('a system colour outside forced-colors', scss('.a { outline: 2px solid CanvasText; }'), ['canvastext']);
  check('a chart dataset literal', ts("const d = { backgroundColor: 'rgba(34, 197, 94, 0.1)' };"), [
    'rgba(34, 197, 94, 0.1)',
  ]);
  check('a named colour as a whole TypeScript string', ts("const c = { color: 'white' };"), ['white']);
  check('a named colour in an inline style', html('<span style="color: white">x</span>'), ['white']);
  check('a literal fill', html('<path fill="#4285F4" d="M0 0"/>'), ['#4285f4']);
  check(
    'a binding in an inline template',
    ts('@Component({ template: `<mat-icon [style.color]="c">x</mat-icon>` })\nclass A {}'),
    ['[style.color]']
  );
  check(
    'a swap inside one file is a new token and a stale one',
    tokenDrift({ '#abd': 1 }, { '#abc': 1 }),
    { over: [['#abd', 1, 0]], under: [['#abc', 0, 1]] }
  );
  check('one more of a frozen token', tokenDrift({ '#abc': 2 }, { '#abc': 1 }), {
    over: [['#abc', 2, 1]],
    under: [],
  });
  // A formatter's spacing is not a swap; a hex keeps the length it was written in.
  check(
    'a reformat keeps its token',
    scss('.a { background: RGBA( 0,0 ,0,0.5 ); border-color: var(--text-muted,#666); }'),
    ['rgba(0, 0, 0, 0.5)', 'var(--text-muted, #666)']
  );
  check('a hex keeps its length', scss('.a { color: #FFF; background: #ffffff; }'), ['#fff', '#ffffff']);

  // --- must not hit -------------------------------------------------------
  // The load-bearing half: each shape below is a token, a utility that
  // follows the theme, or a value that is not a colour. A gate that fired on
  // these would be switched off.
  check('a token', scss('.a { color: var(--text-primary); }'), []);
  check('a token in a shorthand', scss('.a { border: 1px solid var(--border-primary); }'), []);
  check(
    'a marked token read',
    ts(
      'const p = {\n' +
        "  grid: read('--border-primary', '#e5e7eb'), // colors:allow(token-fallback) the canvas cannot read a var()\n" +
        '};'
    ),
    []
  );
  check('a token declaration in the global stylesheet', scss(':root {\n  --text-primary: #111827;\n}', { global: true }), []);
  check(
    'utilities that are not palette colours',
    html('<p class="text-xs text-center bg-transparent border border-current text-fg-muted text-income-text">x</p>'),
    []
  );
  check('the same utilities inside @apply', scss('.a { @apply text-xs bg-transparent border-current text-fg-muted; }'), []);
  check(
    'arbitrary values that are not colours',
    scss(".a { @apply w-[calc(100%-1rem)] grid-cols-[repeat(2,minmax(0,1fr))] bg-[var(--surface-card)] font-['Tan'] data-[state=open]:text-fg; }"),
    []
  );
  check('an alias without an alpha', html('<p class="bg-brand text-fg-secondary border-line-strong">x</p>'), []);
  check('a font size with a line height', html('<p class="text-sm/6">x</p>'), []);
  check('a var() is not a palette utility', scss('.a { color: var(--text-gray-500); }'), []);
  check(
    'a color-mix() over declared tokens',
    scss('.a { background: color-mix(in srgb, var(--color-error) 8%, var(--surface-card)); }'),
    []
  );
  check(
    'a color-mix() over a Material system token',
    scss('.a { background: color-mix(in srgb, var(--color-primary) 30%, var(--mat-sys-surface)); }'),
    []
  );
  check('a color-mix() with currentColor', scss('.a { border-color: color-mix(in srgb, currentColor 20%, transparent); }'), []);
  check('a non-colour fallback', scss('html { font-size: calc(100% * var(--app-font-scale, 1)); }'), []);
  check('a Material token given a length', scss('.a { --mat-icon-button-state-layer-size: 40px; }'), []);
  check('an interpolated !important', scss('.a { @apply text-fg #{!important}; color: var(--text-primary) #{!important}; }'), []);
  // Inside a block and after a colon, where an unmasked comment would read as
  // a declaration's value; before a rule it would only be a selector.
  check(
    'an issue number on a block-comment continuation line',
    scss('.a {\n  /* the swatch used to be\n     white: issue #219 */\n  color: var(--text-primary);\n}'),
    []
  );
  check('a line comment naming a hex', scss('.a {\n  // was: #fff before the sweep\n  color: var(--text-primary);\n}'), []);
  check('white-space', scss('.a { white-space: nowrap; }'), []);
  check('transparent and currentColor', scss('.a { background: transparent; color: currentColor; }'), []);
  check('a named colour inside a font family', scss(".a { font-family: 'Tan', sans-serif; transition: color 0.2s; }"), []);
  check(
    'a system colour inside forced-colors',
    scss('@media (forced-colors: active) {\n  .a { outline: 2px solid CanvasText; }\n}'),
    []
  );
  check(
    'a marked brand block',
    scss('/* colors:allow-start(brand) the provider\'s own mark */\n.google { color: #4285f4; }\n/* colors:allow-end */'),
    []
  );
  check(
    'a marker before a multi-line tag covers the tag',
    html('<!-- colors:allow(brand) the provider\'s own logo -->\n<path\n  fill="#4285F4"\n  d="M0 0"/>'),
    []
  );
  check('a template comment naming a colour', html('<!-- was <p style="color: red"> -->\n<p class="text-fg">x</p>'), []);
  check('a template reference is not a hex', html('<input #abc #face (keyup)="go(abc)">'), []);
  check('an href fragment is not a hex', html('<a href="#main-content">x</a>'), []);
  check('a string-literal var() binding', html(`<mat-icon [style.color]="'var(--text-primary)'"></mat-icon>`), []);
  check(
    'a binding in the category chip',
    ts('@Component({ template: `<span [style.color]="getTextColor(c)">x</span>` })\nclass C {}', {
      file: 'src/app/shared/components/category-chip/category-chip.component.ts',
    }),
    []
  );
  check(
    'a binding inside an allow block',
    html(
      '<!-- colors:allow-start(category-data) the bar is the category\'s own fill -->\n' +
        '<div [style.background-color]="c"></div>\n' +
        '<!-- colors:allow-end -->'
    ),
    []
  );
  check('a hex inside a TypeScript comment', ts('// see #219\n/* and #abc */\nconst a = 1;'), []);
  check(
    'a quote inside a regex literal does not open a string',
    ts("const re = /'/g; // was #abc\nconst ok = 'fine';"),
    []
  );
  check('a template interpolation inside a string', ts('const s = `${a ? "x" : "y"} text-fg`;'), []);

  // --- category -----------------------------------------------------------
  check(
    'a category colour fallback is a category hit',
    kept('ts', "return category?.color || '#9E9E9E';").map((hit) => [hit.token, hit.category]),
    [['#9e9e9e', true]]
  );
  check(
    'a nullish category colour fallback is a category hit',
    kept('html', `<app-x [color]="category()?.color ?? '#666'"></app-x>`).map((hit) => hit.category),
    [true]
  );
  check(
    'a bound colour is a category hit',
    kept('html', '<div [style.color]="c"></div>').map((hit) => hit.category),
    [true]
  );
  check(
    'any other literal is not',
    kept('ts', "const c = { borderColor: '#22c55e' };").map((hit) => hit.category),
    [false]
  );

  // --- markers ------------------------------------------------------------
  check(
    'a marker counts what it exempts, by kind',
    review('ts', "const T = {\n  light: '#3F51B5', // colors:allow(browser-chrome) the browser paints it\n};", { declared })
      .exempted,
    { 'browser-chrome': 1 }
  );
  check(
    'a block counts every hit inside it',
    review(
      'ts',
      '// colors:allow-start(category-data) the seeded categories\nconst C = [\n  \'#ef4444\',\n  \'#f97316\',\n];\n// colors:allow-end',
      { declared }
    ).exempted,
    { 'category-data': 2 }
  );
  check(
    'an empty reason fails',
    review('scss', '.a { color: #abc; } /* colors:allow(brand) */', { declared }).errors.length > 0,
    true
  );
  check(
    'an empty reason on a block fails',
    review('scss', '/* colors:allow-start(brand) */\n.a { color: #abc; }\n/* colors:allow-end */', { declared })
      .errors.length > 0,
    true
  );
  check(
    'an unknown kind fails',
    review('scss', '.a { color: #abc; } /* colors:allow(pretty) it looks nice */', { declared }).errors.length > 0,
    true
  );
  check(
    'a block that never closes fails',
    review('scss', '/* colors:allow-start(brand) the mark */\n.a { color: #abc; }', { declared }).errors.length > 0,
    true
  );
  check(
    'a marker that exempts nothing fails',
    review('scss', '.a { color: var(--text-primary); } /* colors:allow(brand) the mark */', { declared }).errors
      .length > 0,
    true
  );
  // A marker is a comment. Text that spells one in a string or an attribute
  // value is data, and exempts nothing.
  check(
    'a marker spelled inside a TypeScript string',
    ts("const s = 'colors:allow(brand) because'; const c = '#fff';"),
    ['#fff']
  );
  check(
    'a marker spelled inside a stylesheet string',
    scss(".a { content: 'colors:allow(brand) the mark'; color: #abc; }"),
    ['#abc']
  );
  check(
    'a marker spelled inside a template attribute',
    html('<p title="colors:allow(brand) the mark" style="color: red">x</p>'),
    ['red']
  );
  check(
    'a comment marker after a string that spells one',
    review('ts', "const c = '#fff'; const s = 'colors:allow(brand) x'; // colors:allow(brand) the mark", { declared })
      .exempted,
    { brand: 1 }
  );
  // An inline template is a string to the lexer, so it is marked from outside.
  check(
    'a block around an inline template',
    review(
      'ts',
      '@Component({\n  // colors:allow-start(category-data) the bar is the category\'s own fill\n' +
        '  template: `<div [style.background-color]="c"></div>`,\n  // colors:allow-end\n})\nclass A {}',
      { declared }
    ).exempted,
    { 'category-data': 1 }
  );

  // --- reporting ----------------------------------------------------------
  check('line numbers survive masking', scanScss('/* one\n   two */\n.a { color: #abc; }', { declared })[0]?.line, 3);
  check('line numbers survive masking in a template', scanHtml('<!--\n-->\n<p style="color: red">x</p>')[0]?.line, 3);
  check('a valid allowed row', allowedRowValid({ kind: 'brand', count: 2, reason: 'the provider mark' }), true);
  check('an allowed row with an empty reason', allowedRowValid({ kind: 'brand', count: 2, reason: '' }), false);
  check('an allowed row with an unknown kind', allowedRowValid({ kind: 'pretty', count: 2, reason: 'x' }), false);
  check('an allowed row with no hits', allowedRowValid({ kind: 'brand', count: 0, reason: 'x' }), false);
  const row = (kind, count) => ({ kind, count, reason: 'the provider mark' });
  check('an allowed row that matches its markers', allowedDrift({ brand: 3 }, row('brand', 3)), []);
  check('a marker that widened', allowedDrift({ brand: 4 }, row('brand', 3)).length, 1);
  check('a marker that narrowed', allowedDrift({ brand: 2 }, row('brand', 3)).length, 1);
  check('a row whose markers are gone', allowedDrift({}, row('brand', 3)).length, 1);
  check('markers with no row', allowedDrift({ scrim: 2 }, undefined).length, 1);
  check('a file that marks two kinds', allowedDrift({ brand: 6, scrim: 2 }, [row('brand', 6), row('scrim', 2)]), []);
  check('a second kind with no row', allowedDrift({ brand: 6, scrim: 2 }, row('brand', 6)).length, 1);
  check('a row with an empty reason drifts', allowedDrift({ brand: 1 }, { kind: 'brand', count: 1, reason: ' ' }).length, 1);
  check('every allowed row is valid', Object.values(ALLOWED).flatMap(rowsOf).every(allowedRowValid), true);

  let failed = 0;
  for (const result of results) {
    if (result.ok) {
      console.log(`  ok  ${result.name}`);
    } else {
      failed += 1;
      console.error(`  FAIL ${result.name}`);
      console.error(`       expected ${JSON.stringify(result.expected)}`);
      console.error(`       actual   ${JSON.stringify(result.actual)}`);
    }
  }

  if (failed > 0) {
    console.error(`\n${failed} self-test failure(s) — the checker itself is broken.`);
    process.exit(1);
  }
  console.log(`check-colors self-test: ${results.length} passed`);
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  if (process.argv.includes('--self-test')) selfTest();
  else if (process.argv.includes('--print-baseline')) printBaseline();
  else run();
}
