import UIKit
import Capacitor

/// Hosts the Capacitor bridge and registers the plugins that live in this app target.
///
/// `packageClassList` in capacitor.config.json is generated by the Capacitor CLI from the
/// packages it resolves under node_modules, so plugins compiled straight into the app
/// target never appear there and are never picked up by auto-registration.
/// `registerPluginType(_:)` is not a way around it either — it returns immediately while
/// `autoRegisterPlugins` is true, which it always is for `CAPBridgeViewController`.
/// `registerPluginInstance(_:)` carries no such guard, so it is the supported entry point.
///
/// Main.storyboard has to point at this class; if it instantiates `CAPBridgeViewController`
/// directly again, both plugins silently go missing and every call to them rejects with
/// `Unimplemented`.
class MainViewController: CAPBridgeViewController {
    override func capacitorDidLoad() {
        super.capacitorDidLoad()

        // Called after the bridge is constructed but before the web view loads, so these
        // are in place by the time any JS can reach for them.
        bridge?.registerPluginInstance(VisionOCRPlugin())
        bridge?.registerPluginInstance(AppleIntelligencePlugin())
        bridge?.registerPluginInstance(ShareIntakePlugin())
    }
}
